repos:
  "http://github.com/defunkt/github":
    "refs/heads/master":
      recipients: [someone@mail.com, someoneelse@mail.com]
    "refs/heads/debug":
      recipients: [someone@mail.com, someoneelse@mail.com]
mailfrom: admin@somecompany.com
