repos:
  "http://github.com/defunkt/github":
    "refs/heads/master":
      recipients: [david@crowdint.com]
    "refs/heads/debug":
      recipients: [david@crowdint.com]
mailfrom: admin@somecompany.com
